//
// <MapboxGL.ShapeSource
//   id="symbolLocationSource"
//   hitbox={{width: 20, height: 20}}
//   onPress={this.onSourceLayerPress}
//   shape={this.state.featureCollection}
// >
//   <MapboxGL.SymbolLayer
//     id="12340"
//     minZoomLevel={1}
//     style={wzrd1.icon}
//   />
//   <MapboxGL.SymbolLayer
//     id="12341"
//     minZoomLevel={1}
//     style={wzrd2.icon}
//   />
//   <MapboxGL.SymbolLayer
//     id="12342"
//     minZoomLevel={1}
//     style={wzrd3.icon}
//   />
//   <MapboxGL.SymbolLayer
//     id="12343"
//     minZoomLevel={1}
//     style={wzrd4.icon}
//   />
//   <MapboxGL.SymbolLayer
//     id="12344"
//     minZoomLevel={1}
//     style={wzrd5.icon}
//   />
// </MapboxGL.ShapeSource>
